### ISSUE TITLE
Help getting started please.

### ISSUE THREAD

**Issue by conandrum** [pipan/subsetsum-php#9]
Hi,
I am an experienced web developer, but have never used composer.
Even so, I managed to install composer 2.x and now I am trying to get something running in my browser.
I am getting 500 errors on the following:
$subsetTable = SubsetSum::builder()
    ->withSet([1, 2, 5])
    ->withTarget(8)
    ->build();

$subset = $subsetTable->getSubset(8);

Composer installed your module in the home of the user I logged in with.
But the above code is run by the apache user - should I transfer your module files somewhere else?
I am certainly doing something wrong.
Please let me know how to do this even though it is probably basic stuff for you.
Thanks in advance

**Comment by pipan** [comment]
Hi, I tried your example on my computer. I have linux installed with apache and php 7.4. My version of composer is 2.1.9. After running `composer require lmn/subsetsum` my file structure looks like this

```
vendor
composer.json
composer.lock
```

Then I created a `index.php` in the same directory, and created a simple example. I basically copied your example. However, there is a difference. At the top of the index.php file I have to require autoload.php file. It's a specific composer file, that "links" libraries to your project.

```
<?php

require_once "vendor/autoload.php";

use SubsetSum\SubsetSum;

$subsetTable = SubsetSum::builder()
    ->withSet([1, 2, 5])
    ->withTarget(8)
    ->build();

$subset = $subsetTable->getSubset(8);

var_dump($subset);
```

You can read more about [composer autloader](https://getcomposer.org/doc/01-basic-usage.md#autoloading). I guess, that might be the issue. If you are new to PHP, and to the concept of autloading then you can read this [documentation](https://www.php.net/manual/en/language.oop5.autoload.php).

If this won't solve your problem let me know. We can take a look into your logs and find out why your local server responds with 500. 

> You don't have to use apache, you can use nginx if you like or other service. I think this library should work with php5, but I am not sure

**Comment by conandrum** [comment]
I just found some time to revisit this issue.
I found out that I had php 7.2 running on this virtual server.
Once I updated to 7.4 the 500 errors are now gone and the program is running OK!
I will update you as I move forward.
Thanks for your help.

**Comment by pipan** [comment]
Thanks for the update. I might find some time at the end of the week and I will take a look, why php7.2 is not supported. At least I will update the documentation and add it as a requirement or fix it if possible and support php7.x

**Comment by pipan** [comment]
https://github.com/pipan/subsetsum-php/pull/11
